import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="py-8 bg-slate-300">
          <div className="container px-2">
            <nav className="flex items-center justify-between">
              <span className="font-bold inline-block mr-4">Logo</span>
              <div className="flex items-center gap-4">
                <Link href="/">Главная</Link>
                <Link href="/about">О нас</Link>
                <Link href="/services">Услуги</Link>
              </div>
            </nav>
          </div>
        </header>
        {children}
        <footer className="py-8 bg-slate-300">My Footer</footer>
      </body>
    </html>
  );
}
